### ISSUE TITLE
这个跑操剩余次数为负数是认真的吗？

### ISSUE THREAD

**Issue by NN708** [HeraldStudio/herald-ios-app#1]
![66D51DA6-EBB1-41C5-BDFD-F03236E44B2F](https://user-images.githubusercontent.com/20534082/58189980-1cdfcb00-7cee-11e9-820c-b4acee0ddda0.jpeg)

**Comment by Sciroccogti** [comment]
哈哈哈哈哈哈哈哈

不过其实我觉得这也挺直白易懂的

**Comment by Wolf-Tungsten** [comment]
已修复
