### ISSUE TITLE
难怪星星这么少

### ISSUE THREAD

**Issue by MoShenGuo** [HeraldStudio/herald-ios-app#3]
难怪星星这么少,啥都不能给,demo还不能用,什么效果也不知道,果断走了

**Comment by Wolf-Tungsten** [comment]
你礼貌吗？哪来的白嫖怪？
首先这是个已经过期的版本，现在维护的版本不是这个。
其次，我放在这里也不是为了什么星星，我为的是我们的用户（尤其是感兴趣App开发的）能找到我们学习并交流。
不给demo就骂街走人？你知道issues是干嘛用的吗？
我建议你出门左转 CSDN 凹，去下载那些付费资源凹，GitHub还不适合你。

**Comment by tusooa** [comment]
Xref: https://github.com/HeraldStudio/herald-ios-app/issues/2#issuecomment-898104568

「没有账号」
没有账号你来这儿干嘛，笑死我了

**Comment by Wolf-Tungsten** [comment]
有必要解释下，为了保障用户数据安全，目前维护的版本不在GitHub开源，如有兴趣了解可以联系我们的开发团队。
